In [ ]:
import numpy as np

In [ ]:
x = np.array([3,4,5])
y = np.array([4,9,7])

In [ ]:
x + y

array([ 7, 13, 12])

In [ ]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [ ]:
x.ndim

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
np.array([[1,2],[3.0,4]]).dtype

dtype('float64')

In [ ]:
np.array([[1,2],[3,4]],float).dtype

dtype('float64')

In [ ]:
x.shape

(2, 2)

In [ ]:
x = np.array([1,2,3,4])
x.sum()

10

In [ ]:
x = np.array([1,2,3,4])
np.sum(x)

10

In [ ]:
x = np.array([1,2,3,4,5,6])
print('beginning x:\n',x)
x_reshape = x.reshape((2,3))
print('reshaped x:\n',x_reshape)

beginning x:
 [1 2 3 4 5 6]
reshaped x:
 [[1 2 3]
 [4 5 6]]

In [ ]:
x_reshape[0,0]

1

In [ ]:
x_reshape[1,2]

6

In [ ]:
print('x before we modify x_reshape:\n',x)
print('x_reshape before we modify x_reshape:\n',x_reshape)
x_reshape[0,0] = 5
print('x_reshape after we modify its top left element:\n',x_reshape)
print('x after we modify top left element of x_reshape:\n',x)

x before we modify x_reshape:
 [1 2 3 4 5 6]
x_reshape before we modify x_reshape:
 [[1 2 3]
 [4 5 6]]
x_reshape after we modify its top left element:
 [[5 2 3]
 [4 5 6]]
x after we modify top left element of x_reshape:
 [5 2 3 4 5 6]

In [ ]:
x_reshape.shape, x_reshape.ndim, x_reshape.T

((2, 3),
 2,
 array([[5, 4],
        [2, 5],
        [3, 6]]))

In [ ]:
np.sqrt(x)

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [ ]:
x**2

array([25,  4,  9, 16, 25, 36])

In [ ]:
x**0.5

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [ ]:
x = np.random.normal(size=50)
x

array([ 1.10821212, -0.95406028,  1.74059794, -1.59973277,  1.73160606,
       -1.38776283,  1.51181482,  1.51895503, -1.14304526, -0.41451756,
       -0.83940133,  0.8220882 ,  0.27171997,  0.87483559, -1.08321501,
        0.22545774,  0.8715682 ,  0.78490734,  2.46468788, -1.38449521,
       -1.46469531,  0.98320033,  0.47808595, -0.9849598 ,  0.28663004,
       -1.46606876, -0.39082671,  0.55192926,  0.86503749,  1.11777132,
       -1.07267392, -1.03812644,  0.50345712, -0.17256622, -1.69982893,
       -0.85952178,  0.06473355, -1.5975216 , -1.37480227, -0.88341886,
        0.44466911, -1.29786283, -1.18451617,  0.30412499,  0.07333234,
        0.26705083,  1.71978893, -0.8418095 ,  0.83030528,  0.36898929])

In [ ]:
y = x + np.random.normal(loc=50, scale=1, size=50)
y

array([49.80986871, 48.28656246, 52.73230642, 49.49639398, 51.07973733,
       49.81991801, 51.30782637, 51.6481556 , 49.02047921, 50.57211309,
       48.68516939, 51.21463731, 50.68331738, 52.0384109 , 47.93090332,
       52.68519042, 49.91661362, 49.92337612, 52.32064732, 47.72535246,
       48.40664856, 50.60858375, 51.08348768, 51.11192227, 50.73607174,
       47.56825325, 48.81341139, 48.98533114, 49.06654635, 50.45637421,
       48.59426538, 48.00685537, 50.64105811, 49.6164884 , 48.17602579,
       48.74918957, 49.7914176 , 49.03913287, 46.58741738, 48.06314845,
       51.19372524, 47.52654251, 48.43116148, 49.02923069, 50.29864924,
       49.9454487 , 52.70540991, 50.66724801, 50.91177468, 50.01092352])

In [ ]:
np.corrcoef(x,y)

array([[1.        , 0.76531358],
       [0.76531358, 1.        ]])

In [ ]:
print(np.random.normal(scale=5, size=2))
print(np.random.normal(scale=5, size=2))

[-8.43036587  2.89303122]
[6.73359061 7.35389894]

In [ ]:
rng = np.random.default_rng(1303)
print(rng.normal(scale=5, size=2))
rng2 = np.random.default_rng(1303)
print(rng2.normal(scale=5, size=2))

[ 4.09482632 -1.07485605]
[ 4.09482632 -1.07485605]

In [ ]:
rng = np.random.default_rng(3)
y = rng.standard_normal(10)
np.mean(y), y.mean()

(-0.1126795190952861, -0.1126795190952861)

In [ ]:
np.var(y), y.var(), np.mean((y - y.mean())**2)

(2.7243406406465125, 2.7243406406465125, 2.7243406406465125)

In [ ]:
np.sqrt(np.var(y)), np.std(y)

(1.6505576756498128, 1.6505576756498128)

In [ ]:
X = rng.standard_normal((10,3))
X

array([[ 0.22578661, -0.35263079, -0.28128742],
       [-0.66804635, -1.05515055, -0.39080098],
       [ 0.48194539, -0.23855361,  0.9577587 ],
       [-0.19980213,  0.02425957,  1.54582085],
       [ 0.54510552, -0.50522874, -0.18283897],
       [ 0.54052513,  1.93508803, -0.26962033],
       [-0.24355868,  1.0023136 , -0.88645994],
       [-0.29172023,  0.88253897,  0.58035002],
       [ 0.0915167 ,  0.67010435, -2.82816231],
       [ 1.02130682, -0.95964476, -1.66861984]])

In [ ]:
X.mean(axis=0)

array([ 0.15030588,  0.14030961, -0.34238602])

In [ ]:
X.mean(0)

array([ 0.15030588,  0.14030961, -0.34238602])

In [ ]:
A = np.array(np.arange(16)).reshape((4,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
A[1,2]

6

In [ ]:
A[[1,3]]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15]])

In [ ]:
A[:,[0,2]]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14]])

In [ ]:
A[[1,3],[0,2]]

array([ 4, 14])

In [ ]:
A[[1,3]][:,[0,2]]

array([[ 4,  6],
       [12, 14]])

In [ ]:
idx = np.ix_([1,3],[0,2,3])
A[idx]

array([[ 4,  6,  7],
       [12, 14, 15]])

In [ ]:
A[1:4:2,0:3:2]

array([[ 4,  6],
       [12, 14]])

In [ ]:
keep_rows = np.zeros(A.shape[0],bool)
keep_rows

array([False, False, False, False])

In [ ]:
keep_rows[[1,3]] = True
keep_rows

array([False,  True, False,  True])

In [ ]:
np.all(keep_rows == np.array([0,1,0,1]))

True

In [ ]:
A[np.array([0,1,0,1])]

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
A[keep_rows]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15]])

In [ ]:
keep_cols = np.zeros(A.shape[1],bool)
keep_cols[[0,2,3]] = True
idx_bool = np.ix_(keep_rows, keep_cols)
A[idx_bool]

array([[ 4,  6,  7],
       [12, 14, 15]])

In [ ]:
idx_mixed = np.ix_([1,3],keep_cols)
A[idx_mixed]

array([[ 4,  6,  7],
       [12, 14, 15]])

In [ ]:
import pandas as pd
Auto = pd.read_csv('Auto.csv')
Auto

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
392,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
393,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
394,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
395,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
396,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [ ]:
Auto = pd.read_csv('Auto.data', delim_whitespace=True)

In [ ]:
Auto['horsepower']

0      130.0
1      165.0
2      150.0
3      150.0
4      140.0
       ...
392    86.00
393    52.00
394    84.00
395    79.00
396    82.00
Name: horsepower, Length: 397, dtype: object

In [ ]:
Auto = pd.read_csv('Auto.data', na_values=['?'], delim_whitespace=True)
Auto['horsepower'].sum()

40952.0

In [ ]:
Auto.shape

(397, 9)

In [ ]:
Auto_new = Auto.dropna()
Auto_new.shape

(392, 9)

In [ ]:
Auto = Auto_new # overwrite the previous value
Auto.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'year', 'origin', 'name'],
      dtype='object')

In [ ]:
Auto[:3]

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin,name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite

In [ ]:
idx_80 = Auto['year'] > 80
Auto[idx_80]

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin,name
338,27.2,4,135.0,84.0,2490.0,15.7,81,1,plymouth reliant
339,26.6,4,151.0,84.0,2635.0,16.4,81,1,buick skylark
340,25.8,4,156.0,92.0,2620.0,14.4,81,1,dodge aries wagon (sw)
341,23.5,6,173.0,110.0,2725.0,12.6,81,1,chevrolet citation
342,30.0,4,135.0,84.0,2385.0,12.9,81,1,plymouth reliant
343,39.1,4,79.0,58.0,1755.0,16.9,81,3,toyota starlet
344,39.0,4,86.0,64.0,1875.0,16.4,81,1,plymouth champ
345,35.1,4,81.0,60.0,1760.0,16.1,81,3,honda civic 1300
346,32.3,4,97.0,67.0,2065.0,17.8,81,3,subaru
347,37.0,4,85.0,65.0,1975.0,19.4,81,3,datsun 210 mpg
348,37.7,4,89.0,62.0,2050.0,17.3,81,3,toyota tercel
349,34.1,4,91.0,68.0,1985.0,16.0,81,3,mazda glc 4
350,34.7,4,105.0,63.0,2215.0,14.9,81,1,plymouth horizon 4
351,34.4,4,98.0,65.0,2045.0,16.2,81,1,ford escort 4w
352,29.9,4,98.0,65.0,2380.0,20.7,81,1,ford escort 2h
353,33.0,4,105.0,74.0,2190.0,14.2,81,2,volkswagen jetta
355,33.7,4,107.0,75.0,2210.0,14.4,81,3,honda prelude
356,32.4,4,108.0,75.0,2350.0,16.8,81,3,toyota corolla
357,32.9,4,119.0,100.0,2615.0,14.8,81,3,datsun 200sx
358,31.6,4,120.0,74.0,2635.0,18.3,81,3,mazda 626
359,28.1,4,141.0,80.0,3230.0,20.4,81,2,peugeot 505s turbo diesel
360,30.7,6,145.0,76.0,3160.0,19.6,81,2,volvo diesel
361,25.4,6,168.0,116.0,2900.0,12.6,81,3,toyota cressida
362,24.2,6,146.0,120.0,2930.0,13.8,81,3,datsun 810 maxima
363,22.4,6,231.0,110.0,3415.0,15.8,81,1,buick century
364,26.6,8,350.0,105.0,3725.0,19.0,81,1,oldsmobile cutlass ls
365,20.2,6,200.0,88.0,3060.0,17.1,81,1,ford granada gl
366,17.6,6,225.0,85.0,3465.0,16.6,81,1,chrysler lebaron salon
367,28.0,4,112.0,88.0,2605.0,19.6,82,1,chevrolet cavalier
368,27.0,4,112.0,88.0,2640.0,18.6,82,1,chevrolet cavalier wagon
369,34.0,4,112.0,88.0,2395.0,18.0,82,1,chevrolet cavalier 2-door
370,31.0,4,112.0,85.0,2575.0,16.2,82,1,pontiac j2000 se hatchback
371,29.0,4,135.0,84.0,2525.0,16.0,82,1,dodge aries se
372,27.0,4,151.0,90.0,2735.0,18.0,82,1,pontiac phoenix
373,24.0,4,140.0,92.0,2865.0,16.4,82,1,ford fairmont futura
374,36.0,4,105.0,74.0,1980.0,15.3,82,2,volkswagen rabbit l
375,37.0,4,91.0,68.0,2025.0,18.2,82,3,mazda glc custom l
376,31.0,4,91.0,68.0,1970.0,17.6,82,3,mazda glc custom
377,38.0,4,105.0,63.0,2125.0,14.7,82,1,plymouth horizon miser
378,36.0,4,98.0,70.0,2125.0,17.3,82,1,mercury lynx l
379,36.0,4,120.0,88.0,2160.0,14.5,82,3,nissan stanza xe
380,36.0,4,107.0,75.0,2205.0,14.5,82,3,honda accord
381,34.0,4,108.0,70.0,2245.0,16.9,82,3,toyota corolla
382,38.0,4,91.0,67.0,1965.0,15.0,82,3,honda civic
383,32.0,4,91.0,67.0,1965.0,15.7,82,3,honda civic (auto)
384,38.0,4,91.0,67.0,1995.0,16.2,82,3,datsun 310 gx
385,25.0,6,181.0,110.0,2945.0,16.4,82,1,buick century limited
386,38.0,6,262.0,85.0,3015.0,17.0,82,1,oldsmobile cutlass ciera (diesel)
387,26.0,4,156.0,92.0,2585.0,14.5,82,1,chrysler lebaron medallion
388,22.0,6,232.0,112.0,2835.0,14.7,82,1,ford granada l
389,32.0,4,144.0,96.0,2665.0,13.9,82,3,toyota celica gt
390,36.0,4,135.0,84.0,2370.0,13.0,82,1,dodge charger 2.2
391,27.0,4,151.0,90.0,2950.0,17.3,82,1,chevrolet camaro
392,27.0,4,140.0,86.0,2790.0,15.6,82,1,ford mustang gl
393,44.0,4,97.0,52.0,2130.0,24.6,82,2,vw pickup
394,32.0,4,135.0,84.0,2295.0,11.6,82,1,dodge rampage
395,28.0,4,120.0,79.0,2625.0,18.6,82,1,ford ranger
396,31.0,4,119.0,82.0,2720.0,19.4,82,1,chevy s-10

In [ ]:
Auto[['mpg','horsepower']]

      mpg  horsepower
0    18.0       130.0
1    15.0       165.0
2    18.0       150.0
3    16.0       150.0
4    17.0       140.0
..    ...         ...
392  27.0        86.0
393  44.0        52.0
394  32.0        84.0
395  28.0        79.0
396  31.0        82.0

[392 rows x 2 columns]

In [ ]:
Auto.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       387, 388, 389, 390, 391, 392, 393, 394, 395, 396],
      dtype='int64', length=392)

In [ ]:
Auto_re = Auto.set_index('name')
Auto_re

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin
name,,,,,,,,
chevrolet chevelle malibu,18.0,8,307.0,130.0,3504.0,12.0,70,1
buick skylark 320,15.0,8,350.0,165.0,3693.0,11.5,70,1
plymouth satellite,18.0,8,318.0,150.0,3436.0,11.0,70,1
amc rebel sst,16.0,8,304.0,150.0,3433.0,12.0,70,1
ford torino,17.0,8,302.0,140.0,3449.0,10.5,70,1
...,...,...,...,...,...,...,...,...
ford mustang gl,27.0,4,140.0,86.0,2790.0,15.6,82,1
vw pickup,44.0,4,97.0,52.0,2130.0,24.6,82,2
dodge rampage,32.0,4,135.0,84.0,2295.0,11.6,82,1
ford ranger,28.0,4,120.0,79.0,2625.0,18.6,82,1
chevy s-10,31.0,4,119.0,82.0,2720.0,19.4,82,1

In [ ]:
Auto_re.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'year', 'origin'],
      dtype='object')

In [ ]:
rows = ['amc rebel sst','ford torino']
Auto_re.loc[rows]

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin
name,,,,,,,,
amc rebel sst,16.0,8,304.0,150.0,3433.0,12.0,70,1
ford torino,17.0,8,302.0,140.0,3449.0,10.5,70,1

In [ ]:
Auto_re.iloc[[3,4]]

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin
name,,,,,,,,
amc rebel sst,16.0,8,304.0,150.0,3433.0,12.0,70,1
ford torino,17.0,8,302.0,140.0,3449.0,10.5,70,1

In [ ]:
Auto_re.iloc[:,[0,2,3]]

                            mpg  displacement  horsepower
name
chevrolet chevelle malibu  18.0         307.0       130.0
buick skylark 320          15.0         350.0       165.0
plymouth satellite         18.0         318.0       150.0
amc rebel sst              16.0         304.0       150.0
ford torino                17.0         302.0       140.0
...                         ...           ...         ...
ford mustang gl            27.0         140.0        86.0
vw pickup                  44.0          97.0        52.0
dodge rampage              32.0         135.0        84.0
ford ranger                28.0         120.0        79.0
chevy s-10                 31.0         119.0        82.0

[392 rows x 3 columns]

In [ ]:
Auto_re.iloc[[3,4],[0,2,3]]

                mpg  displacement  horsepower
name
amc rebel sst  16.0         304.0       150.0
ford torino    17.0         302.0       140.0

In [ ]:
Auto_re.loc['ford galaxie 500',['mpg','origin']]

                   mpg  origin
name
ford galaxie 500  15.0       1
ford galaxie 500  14.0       1
ford galaxie 500  14.0       1

In [ ]:
idx_80 = Auto_re['year'] > 80
Auto_re.loc[idx_80, ['weight','origin']]

                                   weight  origin
name
plymouth reliant                   2490.0       1
buick skylark                      2635.0       1
dodge aries wagon (sw)             2620.0       1
chevrolet citation                 2725.0       1
plymouth reliant                   2385.0       1
toyota starlet                     1755.0       3
plymouth champ                     1875.0       1
honda civic 1300                   1760.0       3
subaru                             2065.0       3
datsun 210 mpg                     1975.0       3
toyota tercel                      2050.0       3
mazda glc 4                        1985.0       3
plymouth horizon 4                 2215.0       1
ford escort 4w                     2045.0       1
ford escort 2h                     2380.0       1
volkswagen jetta                   2190.0       2
honda prelude                      2210.0       3
toyota corolla                     2350.0       3
datsun 200sx                       2615.0       3
mazda 626                          2635.0       3
peugeot 505s turbo diesel          3230.0       2
volvo diesel                       3160.0       2
toyota cressida                    2900.0       3
datsun 810 maxima                  2930.0       3
buick century                      3415.0       1
oldsmobile cutlass ls              3725.0       1
ford granada gl                    3060.0       1
chrysler lebaron salon             3465.0       1
chevrolet cavalier                 2605.0       1
chevrolet cavalier wagon           2640.0       1
chevrolet cavalier 2-door          2395.0       1
pontiac j2000 se hatchback         2575.0       1
dodge aries se                     2525.0       1
pontiac phoenix                    2735.0       1
ford fairmont futura               2865.0       1
volkswagen rabbit l                1980.0       2
mazda glc custom l                 2025.0       3
mazda glc custom                   1970.0       3
plymouth horizon miser             2125.0       1
mercury lynx l                     2125.0       1
nissan stanza xe                   2160.0       3
honda accord                       2205.0       3
toyota corolla                     2245.0       3
honda civic                        1965.0       3
honda civic (auto)                 1965.0       3
datsun 310 gx                      1995.0       3
buick century limited              2945.0       1
oldsmobile cutlass ciera (diesel)  3015.0       1
chrysler lebaron medallion         2585.0       1
ford granada l                     2835.0       1
toyota celica gt                   2665.0       3
dodge charger 2.2                  2370.0       1
chevrolet camaro                   2950.0       1
ford mustang gl                    2790.0       1
vw pickup                          2130.0       2
dodge rampage                      2295.0       1
ford ranger                        2625.0       1
chevy s-10                         2720.0       1

In [ ]:
Auto_re.loc[lambda df : df['year'] > 80, ['weight','origin']]

                                   weight  origin
name
plymouth reliant                   2490.0       1
buick skylark                      2635.0       1
dodge aries wagon (sw)             2620.0       1
chevrolet citation                 2725.0       1
plymouth reliant                   2385.0       1
toyota starlet                     1755.0       3
plymouth champ                     1875.0       1
honda civic 1300                   1760.0       3
subaru                             2065.0       3
datsun 210 mpg                     1975.0       3
toyota tercel                      2050.0       3
mazda glc 4                        1985.0       3
plymouth horizon 4                 2215.0       1
ford escort 4w                     2045.0       1
ford escort 2h                     2380.0       1
volkswagen jetta                   2190.0       2
honda prelude                      2210.0       3
toyota corolla                     2350.0       3
datsun 200sx                       2615.0       3
mazda 626                          2635.0       3
peugeot 505s turbo diesel          3230.0       2
volvo diesel                       3160.0       2
toyota cressida                    2900.0       3
datsun 810 maxima                  2930.0       3
buick century                      3415.0       1
oldsmobile cutlass ls              3725.0       1
ford granada gl                    3060.0       1
chrysler lebaron salon             3465.0       1
chevrolet cavalier                 2605.0       1
chevrolet cavalier wagon           2640.0       1
chevrolet cavalier 2-door          2395.0       1
pontiac j2000 se hatchback         2575.0       1
dodge aries se                     2525.0       1
pontiac phoenix                    2735.0       1
ford fairmont futura               2865.0       1
volkswagen rabbit l                1980.0       2
mazda glc custom l                 2025.0       3
mazda glc custom                   1970.0       3
plymouth horizon miser             2125.0       1
mercury lynx l                     2125.0       1
nissan stanza xe                   2160.0       3
honda accord                       2205.0       3
toyota corolla                     2245.0       3
honda civic                        1965.0       3
honda civic (auto)                 1965.0       3
datsun 310 gx                      1995.0       3
buick century limited              2945.0       1
oldsmobile cutlass ciera (diesel)  3015.0       1
chrysler lebaron medallion         2585.0       1
ford granada l                     2835.0       1
toyota celica gt                   2665.0       3
dodge charger 2.2                  2370.0       1
chevrolet camaro                   2950.0       1
ford mustang gl                    2790.0       1
vw pickup                          2130.0       2
dodge rampage                      2295.0       1
ford ranger                        2625.0       1
chevy s-10                         2720.0       1

In [ ]:
Auto_re.loc[lambda df: (df['year'] > 80) & (df['mpg'] > 30),
            ['weight','origin']]

                                   weight  origin
name
toyota starlet                     1755.0       3
plymouth champ                     1875.0       1
honda civic 1300                   1760.0       3
subaru                             2065.0       3
datsun 210 mpg                     1975.0       3
toyota tercel                      2050.0       3
mazda glc 4                        1985.0       3
plymouth horizon 4                 2215.0       1
ford escort 4w                     2045.0       1
volkswagen jetta                   2190.0       2
honda prelude                      2210.0       3
toyota corolla                     2350.0       3
datsun 200sx                       2615.0       3
mazda 626                          2635.0       3
volvo diesel                       3160.0       2
chevrolet cavalier 2-door          2395.0       1
pontiac j2000 se hatchback         2575.0       1
volkswagen rabbit l                1980.0       2
mazda glc custom l                 2025.0       3
mazda glc custom                   1970.0       3
plymouth horizon miser             2125.0       1
mercury lynx l                     2125.0       1
nissan stanza xe                   2160.0       3
honda accord                       2205.0       3
toyota corolla                     2245.0       3
honda civic                        1965.0       3
honda civic (auto)                 1965.0       3
datsun 310 gx                      1995.0       3
oldsmobile cutlass ciera (diesel)  3015.0       1
toyota celica gt                   2665.0       3
dodge charger 2.2                  2370.0       1
vw pickup                          2130.0       2
dodge rampage                      2295.0       1
chevy s-10                         2720.0       1

In [ ]:
Auto_re.loc[lambda df: (df['displacement'] < 300) & (df.index.str.contains('ford') | df.index.str.contains('datsun')), ['weight','origin']]

                       weight  origin
name
ford maverick          2587.0       1
datsun pl510           2130.0       3
datsun pl510           2130.0       3
ford torino 500        3302.0       1
ford mustang           3139.0       1
datsun 1200            1613.0       3
ford pinto runabout    2226.0       1
ford pinto (sw)        2395.0       1
datsun 510 (sw)        2288.0       3
ford maverick          3021.0       1
datsun 610             2379.0       3
ford pinto             2310.0       1
datsun b210            1950.0       3
ford pinto             2451.0       1
datsun 710             2003.0       3
ford maverick          3158.0       1
ford pinto             2639.0       1
datsun 710             2545.0       3
ford pinto             2984.0       1
ford maverick          3012.0       1
ford granada ghia      3574.0       1
datsun b-210           1990.0       3
ford pinto             2565.0       1
datsun f-10 hatchback  1945.0       3
ford granada           3525.0       1
ford mustang ii 2+2    2755.0       1
datsun 810             2815.0       3
ford fiesta            1800.0       1
datsun b210 gx         2070.0       3
ford fairmont (auto)   2965.0       1
ford fairmont (man)    2720.0       1
datsun 510             2300.0       3
datsun 200-sx          2405.0       3
ford fairmont 4        2890.0       1
datsun 210             2020.0       3
datsun 310             2019.0       3
ford fairmont          2870.0       1
datsun 510 hatchback   2434.0       3
datsun 210             2110.0       3
datsun 280-zx          2910.0       3
datsun 210 mpg         1975.0       3
ford escort 4w         2045.0       1
ford escort 2h         2380.0       1
datsun 200sx           2615.0       3
datsun 810 maxima      2930.0       3
ford granada gl        3060.0       1
ford fairmont futura   2865.0       1
datsun 310 gx          1995.0       3
ford granada l         2835.0       1
ford mustang gl        2790.0       1
ford ranger            2625.0       1

In [ ]:
import pandas as pd
college = pd.read_csv('College.csv')
college

,Unnamed: 0,Private,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate
0,Abilene Christian University,Yes,1660,1232,721,23,52,2885,537,7440,3300,450,2200,70,78,18.1,12,7041,60
1,Adelphi University,Yes,2186,1924,512,16,29,2683,1227,12280,6450,750,1500,29,30,12.2,16,10527,56
2,Adrian College,Yes,1428,1097,336,22,50,1036,99,11250,3750,400,1165,53,66,12.9,30,8735,54
3,Agnes Scott College,Yes,417,349,137,60,89,510,63,12960,5450,450,875,92,97,7.7,37,19016,59
4,Alaska Pacific University,Yes,193,146,55,16,44,249,869,7560,4120,800,1500,76,72,11.9,2,10922,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
772,Worcester State College,No,2197,1515,543,4,26,3089,2029,6797,3900,500,1200,60,60,21.0,14,4469,40
773,Xavier University,Yes,1959,1805,695,24,47,2849,1107,11520,4960,600,1250,73,75,13.3,31,9189,83
774,Xavier University of Louisiana,Yes,2097,1915,695,34,61,2793,166,6900,4200,617,781,67,75,14.4,20,8323,49
775,Yale University,Yes,10705,2453,1317,95,99,5217,83,19840,6510,630,2115,96,96,5.8,49,40386,99
776,York College of Pennsylvania,Yes,2989,1855,691,28,63,2988,1726,4990,3560,500,1250,75,75,18.1,28,4509,99

In [ ]:
college2 = pd.read_csv('College.csv', index_col=0)
college3 = college.rename({'Unnamed: 0': 'College'},axis=1)
college3 = college3.set_index('College')
college = college3

In [ ]:
pc = pd.DataFrame(college)
print(pc.describe())

               Apps        Accept       Enroll   Top10perc   Top25perc  \
count    777.000000    777.000000   777.000000  777.000000  777.000000
mean    3001.638353   2018.804376   779.972973   27.558559   55.796654
std     3870.201484   2451.113971   929.176190   17.640364   19.804778
min       81.000000     72.000000    35.000000    1.000000    9.000000
25%      776.000000    604.000000   242.000000   15.000000   41.000000
50%     1558.000000   1110.000000   434.000000   23.000000   54.000000
75%     3624.000000   2424.000000   902.000000   35.000000   69.000000
max    48094.000000  26330.000000  6392.000000   96.000000  100.000000

        F.Undergrad   P.Undergrad      Outstate   Room.Board        Books  \
count    777.000000    777.000000    777.000000   777.000000   777.000000
mean    3699.907336    855.298584  10440.669241  4357.526384   549.380952
std     4850.420531   1522.431887   4023.016484  1096.696416   165.105360
min      139.000000      1.000000   2340.000000  1780.000000    96.000000
25%      992.000000     95.000000   7320.000000  3597.000000   470.000000
50%     1707.000000    353.000000   9990.000000  4200.000000   500.000000
75%     4005.000000    967.000000  12925.000000  5050.000000   600.000000
max    31643.000000  21836.000000  21700.000000  8124.000000  2340.000000

          Personal         PhD    Terminal   S.F.Ratio  perc.alumni  \
count   777.000000  777.000000  777.000000  777.000000   777.000000
mean   1340.642214   72.660232   79.702703   14.089704    22.743887
std     677.071454   16.328155   14.722359    3.958349    12.391801
min     250.000000    8.000000   24.000000    2.500000     0.000000
25%     850.000000   62.000000   71.000000   11.500000    13.000000
50%    1200.000000   75.000000   82.000000   13.600000    21.000000
75%    1700.000000   85.000000   92.000000   16.500000    31.000000
max    6800.000000  103.000000  100.000000   39.800000    64.000000

             Expend  Grad.Rate
count    777.000000  777.00000
mean    9660.171171   65.46332
std     5221.768440   17.17771
min     3186.000000   10.00000
25%     6751.000000   53.00000
50%     8377.000000   65.00000
75%    10830.000000   78.00000
max    56233.000000  118.00000